version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing Maven 3.5.2...
      - wget https://archive.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
      - sudo tar xzf apache-maven-3.5.2-bin.tar.gz -C /opt
      - export PATH=/opt/apache-maven-3.5.2/bin:$PATH
      - mvn -version  # verify installation

  pre_build:
    commands:
      - echo Skipping CodeArtifact login since not used
      - echo Preparing build environment...

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -s settings.xml

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging artifacts...
      - mvn package -s settings.xml

artifacts:
  files:
    - target/*.war
  discard-paths: no
